######################################################################
##
## Filename: Controller_FPGA2.udo
## Created on: Mon Aug 29 3:53:26 PM Central Daylight Time 2016
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
