######################################################################
##
## Filename: Controller_FPGA2_tb.udo
## Created on: Mon Mar 21 10:48:52 AM Central Daylight Time 2016
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
