onerror {resume}
quietly virtual signal -install /controller_fpga2_tb/uut { (context /controller_fpga2_tb/uut )(LinkRegHi & LinkRegHi(2 downto 0) &LinkRegLo )} TxDat
quietly virtual signal -install /controller_fpga2_tb/uut { (context /controller_fpga2_tb/uut )( LinkRegHi(2 downto 0) &LinkRegLo )} TxDat001
quietly WaveActivateNextPane {} 0
add wave -noupdate /controller_fpga2_tb/VXO_P
add wave -noupdate /controller_fpga2_tb/VXO_N
add wave -noupdate /controller_fpga2_tb/ClkB_P
add wave -noupdate /controller_fpga2_tb/ClkB_N
add wave -noupdate /controller_fpga2_tb/uut/AuxClk
add wave -noupdate /controller_fpga2_tb/uut/RxFMClk
add wave -noupdate /controller_fpga2_tb/Clk50MHz
add wave -noupdate /controller_fpga2_tb/CpldRst
add wave -noupdate /controller_fpga2_tb/CpldCS
add wave -noupdate /controller_fpga2_tb/uCRd
add wave -noupdate /controller_fpga2_tb/uCWr
add wave -noupdate /controller_fpga2_tb/uCA
add wave -noupdate /controller_fpga2_tb/GA
add wave -noupdate /controller_fpga2_tb/RxDA
add wave -noupdate /controller_fpga2_tb/RxDB
add wave -noupdate /controller_fpga2_tb/RxDC
add wave -noupdate /controller_fpga2_tb/RxDD
add wave -noupdate /controller_fpga2_tb/RxDE
add wave -noupdate /controller_fpga2_tb/RxDF
add wave -noupdate /controller_fpga2_tb/RxDG
add wave -noupdate /controller_fpga2_tb/RxDH
add wave -noupdate /controller_fpga2_tb/RxClk
add wave -noupdate /controller_fpga2_tb/RxDV
add wave -noupdate /controller_fpga2_tb/RxErr
add wave -noupdate /controller_fpga2_tb/CRS
add wave -noupdate /controller_fpga2_tb/TxClk
add wave -noupdate /controller_fpga2_tb/FMRx
add wave -noupdate /controller_fpga2_tb/uBunchFM
add wave -noupdate /controller_fpga2_tb/TrgFM
add wave -noupdate /controller_fpga2_tb/uCD
add wave -noupdate /controller_fpga2_tb/SDD
add wave -noupdate /controller_fpga2_tb/UDQS
add wave -noupdate /controller_fpga2_tb/LDQS
add wave -noupdate /controller_fpga2_tb/SDRzq
add wave -noupdate /controller_fpga2_tb/MDIO
add wave -noupdate /controller_fpga2_tb/SDCKE
add wave -noupdate /controller_fpga2_tb/LDM
add wave -noupdate /controller_fpga2_tb/UDM
add wave -noupdate /controller_fpga2_tb/RAS
add wave -noupdate /controller_fpga2_tb/CAS
add wave -noupdate /controller_fpga2_tb/SDWE
add wave -noupdate /controller_fpga2_tb/SDClk_P
add wave -noupdate /controller_fpga2_tb/SDClk_N
add wave -noupdate /controller_fpga2_tb/SDA
add wave -noupdate /controller_fpga2_tb/BA
add wave -noupdate /controller_fpga2_tb/LinkClk_P
add wave -noupdate /controller_fpga2_tb/LinkClk_N
add wave -noupdate /controller_fpga2_tb/LinkFR_P
add wave -noupdate /controller_fpga2_tb/LinkFR_N
add wave -noupdate /controller_fpga2_tb/LinkD_P
add wave -noupdate /controller_fpga2_tb/LinkD_N
add wave -noupdate /controller_fpga2_tb/TxDA
add wave -noupdate /controller_fpga2_tb/TxDB
add wave -noupdate /controller_fpga2_tb/TxDC
add wave -noupdate /controller_fpga2_tb/TxDD
add wave -noupdate /controller_fpga2_tb/TxDE
add wave -noupdate /controller_fpga2_tb/TxDF
add wave -noupdate /controller_fpga2_tb/TxDG
add wave -noupdate /controller_fpga2_tb/TxDH
add wave -noupdate /controller_fpga2_tb/TxEn
add wave -noupdate /controller_fpga2_tb/iRxClk
add wave -noupdate /controller_fpga2_tb/iRxDV
add wave -noupdate /controller_fpga2_tb/iCRS
add wave -noupdate /controller_fpga2_tb/MDC
add wave -noupdate /controller_fpga2_tb/PhyPDn
add wave -noupdate /controller_fpga2_tb/PhyRst
add wave -noupdate /controller_fpga2_tb/Clk25MHz
add wave -noupdate /controller_fpga2_tb/FMRxEn
add wave -noupdate /controller_fpga2_tb/Debug
add wave -noupdate /controller_fpga2_tb/MDIO_Shift_Out0
add wave -noupdate /controller_fpga2_tb/MDIO_Shift_Out1
add wave -noupdate /controller_fpga2_tb/MDIO_Shift_In0
add wave -noupdate /controller_fpga2_tb/MDIO_Shift_In1
add wave -noupdate /controller_fpga2_tb/MDIO_BitCount
add wave -noupdate /controller_fpga2_tb/MDIO_State
add wave -noupdate /controller_fpga2_tb/RxIns
add wave -noupdate /controller_fpga2_tb/RxOuts
add wave -noupdate /controller_fpga2_tb/NibbleCount
add wave -noupdate /controller_fpga2_tb/RxDatEnable
add wave -noupdate /controller_fpga2_tb/RxDatEnableD
add wave -noupdate /controller_fpga2_tb/VXO_P
add wave -noupdate /controller_fpga2_tb/VXO_N
add wave -noupdate /controller_fpga2_tb/ClkB_P
add wave -noupdate /controller_fpga2_tb/ClkB_N
add wave -noupdate /controller_fpga2_tb/Clk50MHz
add wave -noupdate /controller_fpga2_tb/CpldRst
add wave -noupdate /controller_fpga2_tb/CpldCS
add wave -noupdate /controller_fpga2_tb/uCRd
add wave -noupdate /controller_fpga2_tb/uCWr
add wave -noupdate /controller_fpga2_tb/uCA
add wave -noupdate /controller_fpga2_tb/uut/uCD
add wave -noupdate /controller_fpga2_tb/GA
add wave -noupdate /controller_fpga2_tb/uut/PllLock
add wave -noupdate /controller_fpga2_tb/uut/LockOut
add wave -noupdate /controller_fpga2_tb/uut/BitClk
add wave -noupdate /controller_fpga2_tb/LinkClk_P
add wave -noupdate /controller_fpga2_tb/LinkClk_N
add wave -noupdate /controller_fpga2_tb/LinkFR_P
add wave -noupdate /controller_fpga2_tb/LinkFR_N
add wave -noupdate -expand /controller_fpga2_tb/LinkD_P
add wave -noupdate /controller_fpga2_tb/LinkD_N
add wave -noupdate /controller_fpga2_tb/uut/ClockReg
add wave -noupdate /controller_fpga2_tb/uut/FrameReg
add wave -noupdate /controller_fpga2_tb/uut/TxDat001
add wave -noupdate /controller_fpga2_tb/uut/LinkRegHi
add wave -noupdate /controller_fpga2_tb/uut/LinkRegLo
add wave -noupdate /controller_fpga2_tb/uut/LinkRst
add wave -noupdate /controller_fpga2_tb/uut/LinkTxRdReq
add wave -noupdate /controller_fpga2_tb/uut/TxValid
add wave -noupdate /controller_fpga2_tb/uut/LinkTxEmpty
add wave -noupdate /controller_fpga2_tb/uut/LinkTxFull
add wave -noupdate /controller_fpga2_tb/uut/LinkTxWrReq
add wave -noupdate /controller_fpga2_tb/uut/Loc_Rem
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {164257 ps} 0}
quietly wave cursor active 1
configure wave -namecolwidth 310
configure wave -valuecolwidth 100
configure wave -justifyvalue left
configure wave -signalnamewidth 0
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ns
update
WaveRestoreZoom {124768 ps} {271937 ps}
