######################################################################
##
## Filename: TClk_Tx.udo
## Created on: Mon Aug 29 3:52:39 PM Central Daylight Time 2016
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
